### PR TITLE
Add Catalan translation

### PR DESCRIPTION
**Pull request by J0anJosep**
I have translated the game into Catalan.
There is no emoji for the Catalan flag. I have chosen the "?" flag, although it could be changed with the "Andorra" flag.

Please let me know if I have to modify anything.

### CODE REVIEW

**Comment by SKPG-Tech** [comment]
Sorry, there seems to be a mistake with the mistake checker! Your translation is all good. 
Sorry for the inconvenience. I will fix this soon the next following day, you don't need to do anything further! 

Thank you for translating.

**Comment by SKPG-Tech** [comment]
Everything seems to be in order! I deleted the incorrect comment and fixed the issues. Your translation is mistake-free and is ready to land. I also changed the flag to the one you mentioned. Thanks for doing this!

**Review by SKPG-Tech — APPROVED** [review]

**Comment by SKPG-Tech** [comment]
@J0anJosep a few questions regarding some symbols though. The game doesn't have some of the used symbols in the translation strings and I'd like to ask you about them and what they mean so they can be added to the game.

In this [file](https://github.com/J0anJosep/ppl-i18n/blob/ca-2024-06-28/translations/cat.po#L406-L416), what is the `·` symbol used for and how should it be represented in-game?

As for `‒`, `«` and `ò`, similar characters already exist and can be added no problem!

**Comment by SKPG-Tech** [comment]
Another question. The translations for "off" ("desactivat/da") and "on" ("activat/da") are too long when viewed in-game and cause issues. Can it be written a bit shorter?

image
image

Best case solution should fit inside this small button, if it can't that's fine, but it would be great to be close
image

**Comment by J0anJosep** [comment]
> @J0anJosep a few questions regarding some symbols though. The game doesn't have some of the used symbols in the translation strings and I'd like to ask you about them and what they mean so they can be added to the game.
> 
> In this [file](https://github.com/J0anJosep/ppl-i18n/blob/ca-2024-06-28/translations/cat.po#L406-L416), what is the `·` symbol used for and how should it be represented in-game?
> 
> As for `‒`, `«` and `ò`, similar characters already exist and can be added no problem!

It is a middle dot: https://en.wikipedia.org/wiki/Interpunct#Catalan
It looks exactly as it is shown on GitHub.

**Comment by J0anJosep** [comment]
> Another question. The translations for "off" ("desactivat/da") and "on" ("activat/da") are too long when viewed in-game and cause issues. Can it be written a bit shorter?
> 
> image image
> 
> Best case solution should fit inside this small button, if it can't that's fine, but it would be great to be close image

I will update the PR. "on/off" -> "sí/no". A simple "yes/no" will do the trick.

**Comment by SKPG-Tech** [comment]
I added the special interpunct symbol, how does this look?
image

**Comment by J0anJosep** [comment]
> I added the special interpunct symbol, how does this look?
It looks perfect.

I have fixed a typo and changed the "on/off" translation.
If you need something more, just let me know.

Thank you very much!

**Pull request merged**
