### PR TITLE
Update kaz.po

### PR DESCRIPTION
**Pull request by Qudratillayev**

### CODE REVIEW

**Comment by SKPG-Tech** [comment]
Your changes have been merged in https://github.com/pewpewlive/ppl-i18n/pull/357

**Comment by Qudratillayev** [comment]
Why does the main page say that the Kazakh language is 0% complete?

**Comment by SKPG-Tech** [comment]
The readme updates weekly

**Comment by Qudratillayev** [comment]
Aa, thank you

**Pull request closed without merging**
